# Generated by Django 3.2 on 2022-02-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='float',
            name='category_name',
            field=models.TextField(default=None),
        ),
    ]
