# Generated by Django 3.2 on 2022-02-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_float_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='float',
            old_name='category_name',
            new_name='float_name',
        ),
    ]
