# Generated by Django 3.2 on 2022-03-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='station',
        ),
    ]
