# Generated by Django 3.2 on 2022-03-15 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_category_expense_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='expense_station', to='expense.station'),
        ),
    ]
