# Generated by Django 3.2 on 2022-03-16 09:00

from django.db import migrations, models
import django.utils.timezone
import expense.functions


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_expense_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reciept',
            field=models.FileField(default=django.utils.timezone.now, upload_to=expense.functions.upload_name),
            preserve_default=False,
        ),
    ]
