# Generated by Django 3.2 on 2022-03-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_alter_expense_reciept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='reciept',
            field=models.FileField(upload_to='static/media'),
        ),
    ]
